import {
  MoonIcon,
  CloudMoonIcon,
  WindIcon,
  CloudIcon,
  //   CloudRainWindIcon,
  SnowflakeIcon,
  SunSnowIcon,
  CloudLightningIcon,
  ZapIcon,
  CloudyIcon,
  CloudRainIcon,
  CloudFogIcon,
  CloudMoonRainIcon,
  SunIcon,
  HazeIcon,
  CloudSunIcon,
  CloudSunRainIcon,
  ThermometerSunIcon,
  ThermometerSnowflakeIcon,
  SunDimIcon,
  ChartNoAxesGanttIcon,
  CloudRainWindIcon,
  CloudHailIcon,
  CloudSnowIcon,
  BoxIcon,
  BoxesIcon,
  WavesIcon,
  SunDim,
  MehIcon,
  CloudDrizzleIcon,
} from "lucide-react";
const citySearchQuery = "delhi";
const citySearchData = [
  {
    Version: 1,
    Key: "202396",
    Type: "City",
    Rank: 11,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "",
    Region: {
      ID: "ASI",
      LocalizedName: "Asia",
      EnglishName: "Asia",
    },
    Country: {
      ID: "IN",
      LocalizedName: "India",
      EnglishName: "India",
    },
    AdministrativeArea: {
      ID: "DL",
      LocalizedName: "Delhi",
      EnglishName: "Delhi",
      Level: 1,
      LocalizedType: "Union Territory",
      EnglishType: "Union Territory",
      CountryID: "IN",
    },
    TimeZone: {
      Code: "IST",
      Name: "Asia/Kolkata",
      GmtOffset: 5.5,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 28.643,
      Longitude: 77.118,
      Elevation: {
        Metric: {
          Value: 215,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 705,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "West",
        EnglishName: "West",
      },
      {
        Level: 3,
        LocalizedName: "Rajouri Garden",
        EnglishName: "Rajouri Garden",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "PremiumAirQuality",
    ],
  },
  {
    Version: 1,
    Key: "65329",
    Type: "City",
    Rank: 45,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "",
    Region: {
      ID: "ASI",
      LocalizedName: "Asia",
      EnglishName: "Asia",
    },
    Country: {
      ID: "CN",
      LocalizedName: "China",
      EnglishName: "China",
    },
    AdministrativeArea: {
      ID: "QH",
      LocalizedName: "Qinghai",
      EnglishName: "Qinghai",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "CN",
    },
    TimeZone: {
      Code: "CST",
      Name: "Asia/Shanghai",
      GmtOffset: 8,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 37.369,
      Longitude: 97.361,
      Elevation: {
        Metric: {
          Value: 2987,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 9800,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    ParentCity: {
      Key: "2333285",
      LocalizedName: "Haixi Prefecture",
      EnglishName: "Haixi Prefecture",
    },
    SupplementalAdminAreas: [],
    DataSets: [
      "AirQuality",
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyLocalIndices",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "PremiumAirQuality",
    ],
  },
  {
    Version: 1,
    Key: "2155308",
    Type: "City",
    Rank: 65,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "95315",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "CA",
      LocalizedName: "California",
      EnglishName: "California",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "PDT",
      Name: "America/Los_Angeles",
      GmtOffset: -7,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T09:00:00Z",
    },
    GeoPosition: {
      Latitude: 37.432,
      Longitude: -120.779,
      Elevation: {
        Metric: {
          Value: 36,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 118,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Merced",
        EnglishName: "Merced",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "55137",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "N4B",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "CA",
      LocalizedName: "Canada",
      EnglishName: "Canada",
    },
    AdministrativeArea: {
      ID: "ON",
      LocalizedName: "Ontario",
      EnglishName: "Ontario",
      Level: 1,
      LocalizedType: "Province",
      EnglishType: "Province",
      CountryID: "CA",
    },
    TimeZone: {
      Code: "EDT",
      Name: "America/Toronto",
      GmtOffset: -4,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T06:00:00Z",
    },
    GeoPosition: {
      Latitude: 42.847,
      Longitude: -80.492,
      Elevation: {
        Metric: {
          Value: 238,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 780,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Haldimand-Norfolk",
        EnglishName: "Haldimand-Norfolk",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2971329",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "",
    Region: {
      ID: "ASI",
      LocalizedName: "Asia",
      EnglishName: "Asia",
    },
    Country: {
      ID: "IN",
      LocalizedName: "India",
      EnglishName: "India",
    },
    AdministrativeArea: {
      ID: "MP",
      LocalizedName: "Madhya Pradesh",
      EnglishName: "Madhya Pradesh",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "IN",
    },
    TimeZone: {
      Code: "IST",
      Name: "Asia/Kolkata",
      GmtOffset: 5.5,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 24.634,
      Longitude: 81.565,
      Elevation: {
        Metric: {
          Value: 307,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1006,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Rewa",
        EnglishName: "Rewa",
      },
      {
        Level: 3,
        LocalizedName: "Mangawan",
        EnglishName: "Mangawan",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "FutureRadar",
      "MinuteCast",
      "PremiumAirQuality",
    ],
  },
  {
    Version: 1,
    Key: "2969867",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "",
    Region: {
      ID: "ASI",
      LocalizedName: "Asia",
      EnglishName: "Asia",
    },
    Country: {
      ID: "IN",
      LocalizedName: "India",
      EnglishName: "India",
    },
    AdministrativeArea: {
      ID: "MP",
      LocalizedName: "Madhya Pradesh",
      EnglishName: "Madhya Pradesh",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "IN",
    },
    TimeZone: {
      Code: "IST",
      Name: "Asia/Kolkata",
      GmtOffset: 5.5,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 24.738,
      Longitude: 81.331,
      Elevation: {
        Metric: {
          Value: 184,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 603,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Rewa",
        EnglishName: "Rewa",
      },
      {
        Level: 3,
        LocalizedName: "Sirmour",
        EnglishName: "Sirmour",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "FutureRadar",
      "MinuteCast",
      "PremiumAirQuality",
    ],
  },
  {
    Version: 1,
    Key: "2204223",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "52223",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "IA",
      LocalizedName: "Iowa",
      EnglishName: "Iowa",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 42.43,
      Longitude: -91.331,
      Elevation: {
        Metric: {
          Value: 316,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1036,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Delaware",
        EnglishName: "Delaware",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "333472",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "71232",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "LA",
      LocalizedName: "Louisiana",
      EnglishName: "Louisiana",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 32.458,
      Longitude: -91.493,
      Elevation: {
        Metric: {
          Value: 27,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 88,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Richland",
        EnglishName: "Richland",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2247464",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "56283",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "MN",
      LocalizedName: "Minnesota",
      EnglishName: "Minnesota",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 44.599,
      Longitude: -95.211,
      Elevation: {
        Metric: {
          Value: 313,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1026,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Redwood",
        EnglishName: "Redwood",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "334629",
    Type: "City",
    Rank: 85,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "13753",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "NY",
      LocalizedName: "New York",
      EnglishName: "New York",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "EDT",
      Name: "America/New_York",
      GmtOffset: -4,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T06:00:00Z",
    },
    GeoPosition: {
      Latitude: 42.278,
      Longitude: -74.916,
      Elevation: {
        Metric: {
          Value: 457,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1498,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Delaware",
        EnglishName: "Delaware",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "342594",
    Type: "City",
    Rank: 385,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "81059",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "CO",
      LocalizedName: "Colorado",
      EnglishName: "Colorado",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "MDT",
      Name: "America/Denver",
      GmtOffset: -6,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T08:00:00Z",
    },
    GeoPosition: {
      Latitude: 37.642,
      Longitude: -104.018,
      Elevation: {
        Metric: {
          Value: 1554,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 5100,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Las Animas",
        EnglishName: "Las Animas",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2168804",
    Type: "City",
    Rank: 385,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "30668",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "GA",
      LocalizedName: "Georgia",
      EnglishName: "Georgia",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "EDT",
      Name: "America/New_York",
      GmtOffset: -4,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T06:00:00Z",
    },
    GeoPosition: {
      Latitude: 33.914,
      Longitude: -82.674,
      Elevation: {
        Metric: {
          Value: 162,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 531,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Wilkes",
        EnglishName: "Wilkes",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2240830",
    Type: "City",
    Rank: 385,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "62052",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "IL",
      LocalizedName: "Illinois",
      EnglishName: "Illinois",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 39.045,
      Longitude: -90.256,
      Elevation: {
        Metric: {
          Value: 180,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 590,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Jersey",
        EnglishName: "Jersey",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2126787",
    Type: "City",
    Rank: 385,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "65453",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "MO",
      LocalizedName: "Missouri",
      EnglishName: "Missouri",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 38.128,
      Longitude: -91.348,
      Elevation: {
        Metric: {
          Value: 268,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 879,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Crawford",
        EnglishName: "Crawford",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2138934",
    Type: "City",
    Rank: 385,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "73662",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "OK",
      LocalizedName: "Oklahoma",
      EnglishName: "Oklahoma",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 35.175,
      Longitude: -99.676,
      Elevation: {
        Metric: {
          Value: 586,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 1922,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Beckham",
        EnglishName: "Beckham",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
  {
    Version: 1,
    Key: "2145004",
    Type: "City",
    Rank: 385,
    LocalizedName: "Delhi",
    EnglishName: "Delhi",
    PrimaryPostalCode: "78953",
    Region: {
      ID: "NAM",
      LocalizedName: "North America",
      EnglishName: "North America",
    },
    Country: {
      ID: "US",
      LocalizedName: "United States",
      EnglishName: "United States",
    },
    AdministrativeArea: {
      ID: "TX",
      LocalizedName: "Texas",
      EnglishName: "Texas",
      Level: 1,
      LocalizedType: "State",
      EnglishType: "State",
      CountryID: "US",
    },
    TimeZone: {
      Code: "CDT",
      Name: "America/Chicago",
      GmtOffset: -5,
      IsDaylightSaving: true,
      NextOffsetChange: "2024-11-03T07:00:00Z",
    },
    GeoPosition: {
      Latitude: 29.827,
      Longitude: -97.396,
      Elevation: {
        Metric: {
          Value: 157,
          Unit: "m",
          UnitType: 5,
        },
        Imperial: {
          Value: 514,
          Unit: "ft",
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: "Caldwell",
        EnglishName: "Caldwell",
      },
    ],
    DataSets: [
      "AirQualityCurrentConditions",
      "AirQualityForecasts",
      "Alerts",
      "DailyAirQualityForecast",
      "DailyPollenForecast",
      "ForecastConfidence",
      "FutureRadar",
      "MinuteCast",
      "ProximityNotification-Lightning",
      "Radar",
    ],
  },
];
const forecastDummyData = {
  Headline: {
    EffectiveDate: "2024-09-22T19:00:00+05:30",
    EffectiveEpochDate: 1727011800,
    Severity: 7,
    Text: "Humid Sunday night",
    Category: "humidity",
    EndDate: "2024-09-23T07:00:00+05:30",
    EndEpochDate: 1727055000,
    MobileLink:
      "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?lang=en-us",
    Link: "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?lang=en-us",
  },
  DailyForecasts: [
    {
      Date: "2024-09-21T07:00:00+05:30",
      EpochDate: 1726882200,
      Sun: {
        Rise: "2024-09-21T06:10:00+05:30",
        EpochRise: 1726879200,
        Set: "2024-09-21T18:19:00+05:30",
        EpochSet: 1726922940,
      },
      Moon: {
        Rise: "2024-09-21T20:30:00+05:30",
        EpochRise: 1726930800,
        Set: "2024-09-22T10:44:00+05:30",
        EpochSet: 1726982040,
        Phase: "WaningGibbous",
        Age: 18,
      },
      Temperature: {
        Minimum: {
          Value: 80,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 94,
          Unit: "F",
          UnitType: 18,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 88,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 104,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 88,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 100,
          Unit: "F",
          UnitType: 18,
          Phrase: "Hot",
        },
      },
      HoursOfSun: 7.9,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: "F",
          UnitType: 18,
        },
        Cooling: {
          Value: 22,
          Unit: "F",
          UnitType: 18,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 8,
          Category: "Very High",
          CategoryValue: 4,
        },
      ],
      Day: {
        Icon: 5,
        IconPhrase: "Hazy sunshine",
        HasPrecipitation: false,
        ShortPhrase: "Hazy sun",
        LongPhrase: "Hazy sun",
        PrecipitationProbability: 7,
        ThunderstormProbability: 0,
        RainProbability: 7,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 4.6,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 162,
            Localized: "SSE",
            English: "SSE",
          },
        },
        WindGust: {
          Speed: {
            Value: 11.5,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 162,
            Localized: "SSE",
            English: "SSE",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 37,
        Evapotranspiration: {
          Value: 0.16,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 6844.7,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 54,
          Maximum: 88,
          Average: 67,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 77,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 88,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 86,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Night: {
        Icon: 33,
        IconPhrase: "Clear",
        HasPrecipitation: false,
        ShortPhrase: "Clear",
        LongPhrase: "Clear",
        PrecipitationProbability: 3,
        ThunderstormProbability: 0,
        RainProbability: 3,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 4.6,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 98,
            Localized: "E",
            English: "E",
          },
        },
        WindGust: {
          Speed: {
            Value: 8.1,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 207,
            Localized: "SSW",
            English: "SSW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 7,
        Evapotranspiration: {
          Value: 0.01,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 65,
          Maximum: 87,
          Average: 77,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 77,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 79,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 86,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 84,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=1&lang=en-us",
      Link: "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=1&lang=en-us",
    },
    {
      Date: "2024-09-22T07:00:00+05:30",
      EpochDate: 1726968600,
      Sun: {
        Rise: "2024-09-22T06:10:00+05:30",
        EpochRise: 1726965600,
        Set: "2024-09-22T18:18:00+05:30",
        EpochSet: 1727009280,
      },
      Moon: {
        Rise: "2024-09-22T21:16:00+05:30",
        EpochRise: 1727019960,
        Set: "2024-09-23T11:53:00+05:30",
        EpochSet: 1727072580,
        Phase: "WaningGibbous",
        Age: 19,
      },
      Temperature: {
        Minimum: {
          Value: 80,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 94,
          Unit: "F",
          UnitType: 18,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 88,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 105,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 88,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 101,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      HoursOfSun: 8.6,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: "F",
          UnitType: 18,
        },
        Cooling: {
          Value: 22,
          Unit: "F",
          UnitType: 18,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 8,
          Category: "Very High",
          CategoryValue: 4,
        },
      ],
      Day: {
        Icon: 5,
        IconPhrase: "Hazy sunshine",
        HasPrecipitation: false,
        ShortPhrase: "Hazy sunshine",
        LongPhrase: "Hazy sunshine",
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.8,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 324,
            Localized: "NW",
            English: "NW",
          },
        },
        WindGust: {
          Speed: {
            Value: 10.4,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 295,
            Localized: "WNW",
            English: "WNW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 30,
        Evapotranspiration: {
          Value: 0.17,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 6582,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 55,
          Maximum: 85,
          Average: 66,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 88,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 86,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Night: {
        Icon: 33,
        IconPhrase: "Clear",
        HasPrecipitation: false,
        ShortPhrase: "Clear and humid",
        LongPhrase: "Clear and humid",
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 4.6,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 162,
            Localized: "SSE",
            English: "SSE",
          },
        },
        WindGust: {
          Speed: {
            Value: 8.1,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 245,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 3,
        Evapotranspiration: {
          Value: 0.01,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 65,
          Maximum: 91,
          Average: 80,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 87,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 84,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=2&lang=en-us",
      Link: "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=2&lang=en-us",
    },
    {
      Date: "2024-09-23T07:00:00+05:30",
      EpochDate: 1727055000,
      Sun: {
        Rise: "2024-09-23T06:11:00+05:30",
        EpochRise: 1727052060,
        Set: "2024-09-23T18:16:00+05:30",
        EpochSet: 1727095560,
      },
      Moon: {
        Rise: "2024-09-23T22:07:00+05:30",
        EpochRise: 1727109420,
        Set: "2024-09-24T12:57:00+05:30",
        EpochSet: 1727162820,
        Phase: "WaningGibbous",
        Age: 20,
      },
      Temperature: {
        Minimum: {
          Value: 80,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 96,
          Unit: "F",
          UnitType: 18,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 89,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 106,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 89,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 102,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      HoursOfSun: 11.6,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: "F",
          UnitType: 18,
        },
        Cooling: {
          Value: 23,
          Unit: "F",
          UnitType: 18,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 8,
          Category: "Very High",
          CategoryValue: 4,
        },
      ],
      Day: {
        Icon: 5,
        IconPhrase: "Hazy sunshine",
        HasPrecipitation: false,
        ShortPhrase: "Hazy sunshine",
        LongPhrase: "Hazy sunshine",
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.8,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 287,
            Localized: "WNW",
            English: "WNW",
          },
        },
        WindGust: {
          Speed: {
            Value: 10.4,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 256,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 4,
        Evapotranspiration: {
          Value: 0.21,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 7181.3,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 51,
          Maximum: 87,
          Average: 63,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 82,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 89,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 87,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Night: {
        Icon: 33,
        IconPhrase: "Clear",
        HasPrecipitation: false,
        ShortPhrase: "Clear and humid",
        LongPhrase: "Clear and humid",
        PrecipitationProbability: 5,
        ThunderstormProbability: 0,
        RainProbability: 5,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 3.5,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 238,
            Localized: "WSW",
            English: "WSW",
          },
        },
        WindGust: {
          Speed: {
            Value: 5.8,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 255,
            Localized: "WSW",
            English: "WSW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 0,
        Evapotranspiration: {
          Value: 0.01,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 60,
          Maximum: 86,
          Average: 76,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 88,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 85,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=3&lang=en-us",
      Link: "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=3&lang=en-us",
    },
    {
      Date: "2024-09-24T07:00:00+05:30",
      EpochDate: 1727141400,
      Sun: {
        Rise: "2024-09-24T06:11:00+05:30",
        EpochRise: 1727138460,
        Set: "2024-09-24T18:15:00+05:30",
        EpochSet: 1727181900,
      },
      Moon: {
        Rise: "2024-09-24T23:03:00+05:30",
        EpochRise: 1727199180,
        Set: "2024-09-25T13:55:00+05:30",
        EpochSet: 1727252700,
        Phase: "WaningGibbous",
        Age: 21,
      },
      Temperature: {
        Minimum: {
          Value: 81,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 97,
          Unit: "F",
          UnitType: 18,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 91,
          Unit: "F",
          UnitType: 18,
          Phrase: "Hot",
        },
        Maximum: {
          Value: 107,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 91,
          Unit: "F",
          UnitType: 18,
          Phrase: "Hot",
        },
        Maximum: {
          Value: 102,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      HoursOfSun: 10,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: "F",
          UnitType: 18,
        },
        Cooling: {
          Value: 24,
          Unit: "F",
          UnitType: 18,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 8,
          Category: "Very High",
          CategoryValue: 4,
        },
      ],
      Day: {
        Icon: 5,
        IconPhrase: "Hazy sunshine",
        HasPrecipitation: false,
        ShortPhrase: "Very warm with hazy sunshine",
        LongPhrase: "Very warm with hazy sunshine",
        PrecipitationProbability: 7,
        ThunderstormProbability: 2,
        RainProbability: 7,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 4.6,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 310,
            Localized: "NW",
            English: "NW",
          },
        },
        WindGust: {
          Speed: {
            Value: 9.2,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 329,
            Localized: "NNW",
            English: "NNW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 17,
        Evapotranspiration: {
          Value: 0.19,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 7054.8,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 48,
          Maximum: 82,
          Average: 60,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 80,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 82,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 90,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 87,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Night: {
        Icon: 33,
        IconPhrase: "Clear",
        HasPrecipitation: false,
        ShortPhrase: "Clear, warm and humid",
        LongPhrase: "Clear, warm and humid",
        PrecipitationProbability: 3,
        ThunderstormProbability: 1,
        RainProbability: 3,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 3.5,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 133,
            Localized: "SE",
            English: "SE",
          },
        },
        WindGust: {
          Speed: {
            Value: 8.1,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 205,
            Localized: "SSW",
            English: "SSW",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 0,
        Evapotranspiration: {
          Value: 0.01,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 59,
          Maximum: 90,
          Average: 78,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 79,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 82,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 82,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 87,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 85,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=4&lang=en-us",
      Link: "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=4&lang=en-us",
    },
    {
      Date: "2024-09-25T07:00:00+05:30",
      EpochDate: 1727227800,
      Sun: {
        Rise: "2024-09-25T06:12:00+05:30",
        EpochRise: 1727224920,
        Set: "2024-09-25T18:14:00+05:30",
        EpochSet: 1727268240,
      },
      Moon: {
        Rise: null,
        EpochRise: null,
        Set: "2024-09-25T13:55:00+05:30",
        EpochSet: 1727252700,
        Phase: "Last",
        Age: 22,
      },
      Temperature: {
        Minimum: {
          Value: 78,
          Unit: "F",
          UnitType: 18,
        },
        Maximum: {
          Value: 94,
          Unit: "F",
          UnitType: 18,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 89,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 106,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 89,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Warm",
        },
        Maximum: {
          Value: 101,
          Unit: "F",
          UnitType: 18,
          Phrase: "Very Hot",
        },
      },
      HoursOfSun: 10.6,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: "F",
          UnitType: 18,
        },
        Cooling: {
          Value: 21,
          Unit: "F",
          UnitType: 18,
        },
      },
      AirAndPollen: [
        {
          Name: "AirQuality",
          Value: 0,
          Category: "Good",
          CategoryValue: 1,
          Type: "Ozone",
        },
        {
          Name: "Grass",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Mold",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Ragweed",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "Tree",
          Value: 0,
          Category: "Low",
          CategoryValue: 1,
        },
        {
          Name: "UVIndex",
          Value: 7,
          Category: "High",
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 5,
        IconPhrase: "Hazy sunshine",
        HasPrecipitation: false,
        ShortPhrase: "Hazy sunshine and humid",
        LongPhrase: "Hazy sunshine and humid",
        PrecipitationProbability: 25,
        ThunderstormProbability: 6,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 3.5,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 183,
            Localized: "S",
            English: "S",
          },
        },
        WindGust: {
          Speed: {
            Value: 11.5,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 150,
            Localized: "SSE",
            English: "SSE",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 18,
        Evapotranspiration: {
          Value: 0.19,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 7084.4,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 54,
          Maximum: 88,
          Average: 66,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 79,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 82,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 83,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 89,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 87,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Night: {
        Icon: 34,
        IconPhrase: "Mostly clear",
        HasPrecipitation: false,
        ShortPhrase: "Mainly clear and humid",
        LongPhrase: "Mostly clear and uncomfortably humid",
        PrecipitationProbability: 25,
        ThunderstormProbability: 6,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 4.6,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 127,
            Localized: "SE",
            English: "SE",
          },
        },
        WindGust: {
          Speed: {
            Value: 13.8,
            Unit: "mi/h",
            UnitType: 9,
          },
          Direction: {
            Degrees: 128,
            Localized: "SE",
            English: "SE",
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Rain: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Snow: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        Ice: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 18,
        Evapotranspiration: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: "W/m²",
          UnitType: 33,
        },
        RelativeHumidity: {
          Minimum: 72,
          Maximum: 100,
          Average: 90,
        },
        WetBulbTemperature: {
          Minimum: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 82,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 81,
            Unit: "F",
            UnitType: 18,
          },
        },
        WetBulbGlobeTemperature: {
          Minimum: {
            Value: 79,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 87,
            Unit: "F",
            UnitType: 18,
          },
          Average: {
            Value: 84,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Sources: ["AccuWeather"],
      MobileLink:
        "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=5&lang=en-us",
      Link: "http://www.accuweather.com/en/in/delhi/202396/daily-weather-forecast/202396?day=5&lang=en-us",
    },
  ],
};

const weatherIconPairs = {
  day: {
    Sunny: [SunIcon],
    "Mostly Sunny": [CloudSunIcon],
    "Partly Sunny": [SunDimIcon],
    "Intermittent Clouds": [CloudSunIcon, CloudyIcon],
    "Hazy Sunshine": [HazeIcon],
    "Mostly Cloudy": [CloudIcon],
    "Some Clouds": [CloudIcon],
    Cloudy: [CloudyIcon],
    "Dreary (Overcast)": [CloudyIcon, MehIcon],
    Fog: [WavesIcon],
    Showers: [CloudRainWindIcon],
    "Mostly Cloudy W/ Showers": [CloudyIcon, CloudRainIcon],
    "Partly Sunny W/ Showers": [CloudSunRainIcon],
    "T-storms": [CloudLightningIcon, ZapIcon],
    "Thunderstorms": [CloudLightningIcon, ZapIcon],
    "Mostly Cloudy W/ T-Storms": [CloudLightningIcon],
    "Partly Sunny W/ T-Storms": [CloudLightningIcon, SunDimIcon],
    "Mostly Cloudy W/ T-storms": [CloudLightningIcon],
    "Partly Sunny W/ T-storms": [CloudLightningIcon, SunDimIcon],
    Rain: [CloudRainIcon],
    Flurries: [CloudHailIcon],
    "Mostly Cloudy W/ Flurries": [CloudyIcon, CloudHailIcon],
    "Partly Sunny W/ Flurries": [SunDimIcon, CloudHailIcon],
    Snow: [CloudSnowIcon],
    "Mostly Cloudy W/ Snow": [CloudyIcon, CloudSnowIcon],
    Ice: [BoxesIcon, SnowflakeIcon],
    Sleet: [CloudSnowIcon, CloudHailIcon],
    "Freezing Rain": [CloudRainIcon, ThermometerSnowflakeIcon],
    "Rain and Snow": [CloudRainIcon, CloudSnowIcon],
    Hot: [ThermometerSunIcon],
    Cold: [ThermometerSnowflakeIcon],
    Windy: [WindIcon],
    Hail: [CloudHailIcon],
    Drizzle: [CloudDrizzleIcon],
    Graupel: [CloudRainIcon, SnowflakeIcon],
    "Ice Pellets": [BoxesIcon, SnowflakeIcon],
    "Mixed Precipitation": [CloudHailIcon, CloudRainIcon, CloudSnowIcon],
  },
  night: {
    Cloudy: [CloudyIcon],
    "Some Clouds": [CloudIcon],
    "Dreary (Overcast)": [CloudyIcon, MehIcon],
    Fog: [WavesIcon],
    Showers: [CloudRainWindIcon],
    "T-Storms": [CloudLightningIcon, ZapIcon],
    "Thunderstorms": [CloudLightningIcon, ZapIcon],
    Rain: [CloudRainIcon],
    Flurries: [CloudHailIcon],
    Snow: [CloudSnowIcon],
    Ice: [BoxesIcon, SnowflakeIcon],
    Sleet: [CloudSnowIcon, CloudHailIcon],
    "Freezing Rain": [CloudRainIcon, ThermometerSnowflakeIcon],
    "Rain and Snow": [CloudRainIcon, CloudSnowIcon],
    Hot: [ThermometerSunIcon],
    Cold: [ThermometerSnowflakeIcon],
    Windy: [WindIcon],
    Clear: [MoonIcon],
    "Mostly Clear": [CloudMoonIcon],
    "Partly Cloudy": [CloudMoonIcon],
    "Intermittent Clouds": [CloudMoonIcon, CloudyIcon],
    "Hazy Moonlight": [HazeIcon, MoonIcon],
    "Mostly Cloudy": [CloudIcon],
    "Partly Cloudy W/ Showers": [CloudMoonRainIcon],
    "Mostly Cloudy W/ Showers": [CloudyIcon, CloudRainIcon],
    "Partly Cloudy W/ T-Storms": [CloudLightningIcon, MoonIcon],
    "Mostly Cloudy W/ T-Storms": [CloudLightningIcon],
    "Partly Cloudy W/ T-storms": [CloudLightningIcon, MoonIcon],
    "Mostly Cloudy W/ T-storms": [CloudLightningIcon],
    "Mostly Cloudy W/ Flurries": [CloudyIcon, CloudHailIcon],
    "Mostly Cloudy W/ Snow": [CloudyIcon, CloudSnowIcon],
  },
};

const currentData = [
  {
    LocalObservationDateTime: "2024-09-21T22:21:00+05:30",
    EpochTime: 1726937460,
    WeatherText: "Clear",
    WeatherIcon: 33,
    HasPrecipitation: true,
    PrecipitationType: "Mixed precipitation",
    IsDayTime: false,
    Temperature: {
      Metric: {
        Value: 29.1,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 84,
        Unit: "F",
        UnitType: 18,
      },
    },
    RealFeelTemperature: {
      Metric: {
        Value: 34.1,
        Unit: "C",
        UnitType: 17,
        Phrase: "Hot",
      },
      Imperial: {
        Value: 93,
        Unit: "F",
        UnitType: 18,
        Phrase: "Hot",
      },
    },
    RealFeelTemperatureShade: {
      Metric: {
        Value: 34.1,
        Unit: "C",
        UnitType: 17,
        Phrase: "Hot",
      },
      Imperial: {
        Value: 93,
        Unit: "F",
        UnitType: 18,
        Phrase: "Hot",
      },
    },
    RelativeHumidity: 78,
    IndoorRelativeHumidity: 78,
    DewPoint: {
      Metric: {
        Value: 24.9,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 77,
        Unit: "F",
        UnitType: 18,
      },
    },
    Wind: {
      Direction: {
        Degrees: 23,
        Localized: "NNE",
        English: "NNE",
      },
      Speed: {
        Metric: {
          Value: 7.5,
          Unit: "km/h",
          UnitType: 7,
        },
        Imperial: {
          Value: 4.6,
          Unit: "mi/h",
          UnitType: 9,
        },
      },
    },
    WindGust: {
      Speed: {
        Metric: {
          Value: 9.2,
          Unit: "km/h",
          UnitType: 7,
        },
        Imperial: {
          Value: 5.7,
          Unit: "mi/h",
          UnitType: 9,
        },
      },
    },
    UVIndex: 0,
    UVIndexText: "Low",
    Visibility: {
      Metric: {
        Value: 1.6,
        Unit: "km",
        UnitType: 6,
      },
      Imperial: {
        Value: 1,
        Unit: "mi",
        UnitType: 2,
      },
    },
    ObstructionsToVisibility: "",
    CloudCover: 8,
    Ceiling: {
      Metric: {
        Value: 9144,
        Unit: "m",
        UnitType: 5,
      },
      Imperial: {
        Value: 30000,
        Unit: "ft",
        UnitType: 0,
      },
    },
    Pressure: {
      Metric: {
        Value: 1008,
        Unit: "mb",
        UnitType: 14,
      },
      Imperial: {
        Value: 29.77,
        Unit: "inHg",
        UnitType: 12,
      },
    },
    PressureTendency: {
      LocalizedText: "Rising",
      Code: "R",
    },
    Past24HourTemperatureDeparture: {
      Metric: {
        Value: 0.2,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 0,
        Unit: "F",
        UnitType: 18,
      },
    },
    ApparentTemperature: {
      Metric: {
        Value: 33.9,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 93,
        Unit: "F",
        UnitType: 18,
      },
    },
    WindChillTemperature: {
      Metric: {
        Value: 28.9,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 84,
        Unit: "F",
        UnitType: 18,
      },
    },
    WetBulbTemperature: {
      Metric: {
        Value: 26.2,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 79,
        Unit: "F",
        UnitType: 18,
      },
    },
    WetBulbGlobeTemperature: {
      Metric: {
        Value: 27.3,
        Unit: "C",
        UnitType: 17,
      },
      Imperial: {
        Value: 81,
        Unit: "F",
        UnitType: 18,
      },
    },
    Precip1hr: {
      Metric: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Imperial: {
        Value: 0,
        Unit: "in",
        UnitType: 1,
      },
    },
    PrecipitationSummary: {
      Precipitation: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 1.3,
          Unit: "in",
          UnitType: 1,
        },
      },
      PastHour: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
      Past3Hours: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
      Past6Hours: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
      Past9Hours: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
      Past12Hours: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
      Past18Hours: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
      Past24Hours: {
        Metric: {
          Value: 0,
          Unit: "mm",
          UnitType: 3,
        },
        Imperial: {
          Value: 0,
          Unit: "in",
          UnitType: 1,
        },
      },
    },
    TemperatureSummary: {
      Past6HourRange: {
        Minimum: {
          Metric: {
            Value: 29.1,
            Unit: "C",
            UnitType: 17,
          },
          Imperial: {
            Value: 84,
            Unit: "F",
            UnitType: 18,
          },
        },
        Maximum: {
          Metric: {
            Value: 34.2,
            Unit: "C",
            UnitType: 17,
          },
          Imperial: {
            Value: 94,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Past12HourRange: {
        Minimum: {
          Metric: {
            Value: 29.1,
            Unit: "C",
            UnitType: 17,
          },
          Imperial: {
            Value: 84,
            Unit: "F",
            UnitType: 18,
          },
        },
        Maximum: {
          Metric: {
            Value: 34.2,
            Unit: "C",
            UnitType: 17,
          },
          Imperial: {
            Value: 94,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
      Past24HourRange: {
        Minimum: {
          Metric: {
            Value: 25.5,
            Unit: "C",
            UnitType: 17,
          },
          Imperial: {
            Value: 78,
            Unit: "F",
            UnitType: 18,
          },
        },
        Maximum: {
          Metric: {
            Value: 34.2,
            Unit: "C",
            UnitType: 17,
          },
          Imperial: {
            Value: 94,
            Unit: "F",
            UnitType: 18,
          },
        },
      },
    },
    MobileLink:
      "http://www.accuweather.com/en/in/delhi/202396/current-weather/202396?lang=en-us",
    Link: "http://www.accuweather.com/en/in/delhi/202396/current-weather/202396?lang=en-us",
  },
];

const placeholderCities = [
  "New York",
  "London",
  "Tokyo",
  "Paris",
  "Berlin",
  "Sydney",
  "Toronto",
  "Dubai",
  "Singapore",
  "Hong Kong",
  "Dholakpur",
  "Delhi",
];
export {
  citySearchData,
  forecastDummyData,
  citySearchQuery,
  weatherIconPairs,
  placeholderCities,
  currentData,
};
